web:
  restart: always
  build: ./web
  expose:
    - "5000"
  links:
    - postgres:postgres
    - redis:redis
  environment:
    - MODE=dev
  volumes:
    - /usr/src/app/static
    - ./web:/usr/src:ro
  env_file: .env
  command: /usr/local/bin/python /usr/src/run.py
  #command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app --reload

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
