web:
  restart: always
  build: ./web
  expose:
    - "5000"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
