web:
  extends:
    file: docker-compose.base.yml
    service: web
  # reference static files so that nginx can serve them directly
  volumes:
    - /src/app/static/
  env_file: .env
  # just to be sure that debug is off.
  environment:
    - DEBUG=False
  command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
  links:
    - postgres:postgres
    - redis:redis

nginx:
  extends:
    file: docker-compose.base.yml
    service: nginx
  # references static assets from web
  volumes_from:
    - web
  links:
    - web:web

data:
  extends:
    file: docker-compose.base.yml
    service: data

postgres:
  extends:
    file: docker-compose.base.yml
    service: postgres
  # the same env file defines both the postgres user/password
  # so that postgres creates the user, and the app uses those creds
  env_file: .env
  volumes_from:
    - data

redis:
  extends:
    file: docker-compose.base.yml
    service: redis
