web:
  extends:
    file: docker-compose.base.yml
    service: web
  # mount your working directory to the container, so that code changes
  # are reflected immediately, without requiring rebuilding containers
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  # use built-in flask server for dev. automatically handles code reloading
  command: /usr/local/bin/python /usr/src/app/manage.py runserver
  #command: /usr/local/bin/gunicorn -w 2 -b :8000 run:app --reload
  links:
    - postgres:postgres

nginx:
  extends:
    file: docker-compose.base.yml
    service: nginx
  volumes_from:
    - web
  links:
    - web:web

data:
  extends:
    file: docker-compose.base.yml
    service: data

postgres:
  extends:
    file: docker-compose.base.yml
    service: postgres
  # the same env file defines both the postgres user/password
  # so that postgres creates the user, and the app uses those creds
  env_file: .env
  volumes_from:
    - data
