web:
  extends:
    file: docker-compose.base.yml
    service: web
  # mount your working directory to the container, so that code changes
  # are reflected immediately, without requiring rebuilding containers
  volumes:
    - ./web:/src
  environment:
    - MODE=dev
    - DEBUG=False
    - SECRET_KEY=lol-change-me-plz
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_SERVICE=postgres
    - DB_PORT=5432
  # use built-in flask server for dev. automatically handles code reloading
  command: /usr/local/bin/python /src/run.py
  #command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app --reload
  links:
    - postgres:postgres
    - redis:redis

nginx:
  extends:
    file: docker-compose.base.yml
    service: nginx
  volumes_from:
    - web
  links:
    - web:web

data:
  extends:
    file: docker-compose.base.yml
    service: data

postgres:
  extends:
    file: docker-compose.base.yml
    service: postgres
  volumes_from:
    - data

redis:
  extends:
    file: docker-compose.base.yml
    service: redis
