web:
  restart: always
  build: ./web
  expose:
    - "5000"
  # reference static files so that nginx can serve them directly
  volumes:
    - /usr/src/app/app/static/
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :5000 manage:app
  links:
    - postgres:postgres

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  # references static assets from web
  volumes_from:
    - web
  links:
    - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql

postgres:
  restart: always
  image: postgres:9.5
  ports:
    - "5432:5432"
  # the same env file defines both the postgres user/password
  # so that postgres creates the user, and the app uses those creds
  env_file: .env
  volumes_from:
    - data