web:
  restart: always
  build: ./web
  expose:
    - "5000"
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :5000 manage:app
  links:
    - postgres:postgres

nginx:
  restart: always
  # build also includes static assets to be served by nginx
  build: ./nginx
  ports:
    - "80:80"
  links:
    - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql

postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  # the same env file defines both the postgres user/password
  # so that postgres creates the user, and the app uses those creds
  env_file: .env
  volumes_from:
    - data